dist: xenial
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      python: 3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-tes
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-9
    #   env:
    #     - MATRIX_EVAL="CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user conan cmake ninja

script:
  - pip install --user conan
  - cmake -G Ninja -DENABLE_IPO=OFF .
  - cmake --build . --target gameboy

deploy:
  provider: releases
  api_key:
    secure: Icnzm06WaM5Zj9dP3Jjt6Gy9oO+SioCa7Qy3ejrCjPhyGWzshDT+jPVJuDUvIpc9CrQcNflGO1/tAzYMKjVPK8D70G0/EMRCse404ZbkIWTs1nzBN6oZ7RDAsLxkZfPlGAJutLHdb7rlh4kv3epCSUp0pUHQq6SDNJ71X+uxHJ/So1mgLyoo2frBxM1CNd1JpUeaYRAlovR7og6uc7P0w4/tIsuAuM3UVY2BPCbp2E1VdsZfOE1K9r18cI1oYyY6ng9mly/ghjEIl/GQt8dyUx/RRbIImADq4FERf9MuAIGRp1L+CnhGPMBIIJ/uMvPOpCmb4FvQ55dHmjVrWLw3/KGjRsHUn5QSVNj0IdGSm1b85Za6QBqE4uwA/0PR/tz7zvi5NgZbVUn5w3nLrHEaUABxTXO45hcLlVxm32NljTszKDEEuzaQ87SeJCZrkPYiECgfEHlnIOTYMza/qJcDjMCQo6gelHKhOqC3fSwDrVEsRTPUIJ82uSGn9oFWP72D1mKIJfoQoB2JJbZnGfOTYD5yoYbRWU8W5YyHR0GzMZpZjpm8s74w8INUPLnAYt275OAEzlc6m0NB6Q1B34EYEqCqWU20DEfx53ZmDBbTGWBAiEKg0lJ6j62fAVDaOsARF2kce24u3szfJDQq5fBgx2YuP4x6Q7mHd08pazPtAIQ=
  file: "./bin/gameboy"
  skip_cleanup: true
  on:
    branch: master
