dist: xenial
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      python: 3.8
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
      env:
        - MATRIX_EVAL="CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9 W_LIBCXX=OFF COV=1"

    - os: linux
      python: 3.8
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
      env:
        - MATRIX_EVAL="CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9 W_LIBCXX=ON COV=0"

addons:
  sonarcloud:
    organization: "emrsmsrli"
    token:
      secure: "OpitDZhmDDpaWrJAioy2mOL0bKwTqWG51g4HcPXuwvxaPJbVRF+DoGUYErqxxUdYGj0P/Dx6lu0sMUIhAE+UylLw1KhHcrIuUfAgKUTJo+3mMWlIwQ+4xdDF4IFYHsJ918ogES8hpLHYUb92TdQpNHZ/rz4tgQ43o4Caqk9Lm60oIi7otb3W555wLJjruMWW6/sHMmBjE2zzEefOD7K/v/Uk4mytpg/WiwgYTHiL4lUAagC4TqIXhYpV1n/8OwC5u3RadruFExr4tG6qWzZAnCdjmnNw3W9PIkXeRoE3q48bVqbh8BkdPvY9AB8YrG+k3rNTGE9ukoj/Voob9bGrGxM6Jl8ZyjbppfPq1yxvWypGAsGCO/rVnUg1Ou5b63tX8dNqWMh0/7Mm10lQqRsubeQX9q1mY/QPmbQrBVv+9adcv8MBxeHo6GFOzJ21Le3Erf3R93SXO+VYu4dIeyvA4gMqWzCSah1JTb0wmeIwcEysfQgY9Cbc8Atd5mn0KX78PG3mSq4/phHwMm5UZcIUXaNNpFKZ0gd3ba3dt5SZHcGwVODCytUdUwCApLOMbwr6ck4gAFcLotqcT8UzkcEFd3BGYTXt8o60sWsGyTdnmN6PLHm91YLTTXodl4HjEQJs82AQQX5dGRHSjVasDoibUxCqLc6biDNwlFJm1uvrthU="

before_script:
  - eval "${MATRIX_EVAL}"
  - pip install --user conan cmake ninja

script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DENABLE_COVERAGE=ON -DWITH_LIBCXX=${W_LIBCXX} ..
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build .
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
  - ctest -V --output-on-failure

after_success:
  - chmod +x ./scripts/report_coverage.sh
  - ./scripts/report_coverage.sh

before_deploy:
  - git config --local user.name  "emrsmsrli"
  - git config --local user.email "emrsmsrli1@gmail.com"
  - export RELEASE_TAG=release-$(head -1 gameboy/CMakeLists.txt | awk '{print $3}')-$(git log --format=%h -1)
  - git tag $RELEASE_TAG

deploy:
  provider: releases
  api_key:
    secure: fN18Vwf2TY5blbIx9rNFA1YaP9LW1PnUorSf6jCkFpTpkU7V6J6CF2nSDTjDWJdj0Pf+7nu5laZ6Pd9CwHhkjuGW8iKK0O7ZG7gcM3aicD7msJihR3evzCDtAnW9qxOtZvMJ9XrIQ20DKVaV4s1i7v1ojKlhir+5m8GCoSvc3pt1j2QREypi1hHVJVRtgOXDun5BKwBbyCy2uHSGW6T4NrmA9usejdpaTaJFq2u6VpwsKtmBcoO2+km3OW/MQHFl+KsOsHUNaNAh2ryHjerXD9+Mf13JC11IvKEAGSjGhsrG3tZOXxEWFI+KdktzXh+9ZZLZMUCNeTsbNIlgUpp74vXvoWrbu3a0WsfjUEI7NSUIo86KuSctHLCC0xBQfLGoINdXvVjIdkJIv0eQhxZ4PftOJeJmg8ypYz3U0UFdUMQzE1QXtYBTx8ONpQyTifoRXawNzVzd2vwHURLpZE6jBLNSgJ+xgEhNvRPm8nfBplmldtXGvPQ8UxG4KDcMFzy1IZSbv7ZR06lsz2LlR9XKw7IwSnSiwVImXiG+4SUrKWXcC2qXqbwxc5E+yxBT5i2cqMaHTq6LgacS7SU0xAMzlYoIxdbpSZl8RjTDIIzBFGnICr4cWqCkunTIgNijtoWFr9u5LSasQgolJqoLP+30tDVZW/lJeicQpMYr4FbDgpk=
  file: "./bin/gameboy"
  skip_cleanup: true
  on:
    branch: master
