os: linux
dist: bionic
sudo: false
language: cpp
cache:
  ccache: true
  directories:
    - ./.sonar_cache

branches:
  only:
    - master

addons: &addons_base
  sonarcloud:
    organization: "emrsmsrli"
    token:
      secure: "LzDe005exShyNA/5zNs6pDmSajVBMYv9eN6fWLebqrCJOHlr5e+uVsYcUbfPcF4UKevQP5YZWZXSMuwUeY/HlNU9Gij6Y5aQZAojel/vSb4F5BQVtuJ9Xj3lbXn4AZ87trrFt6XCBcNYf/jmtEFeWARsfhWwrqrIg7FYZPCcSJB0AIuBpRqrONF3jiuR7F1Clnx/OVWCzZYkkVr+qTC6359P1xoMqco8kYkxLkvHg1iOUlD42tkZJz+aH2H3Pc1lvIiFbDfzcWDUY9Gcb4wlaJGbKVytwHP5i5+ExP2x2EnilaTKPOzKLlbu2Yr/OOM9sxvSl2TcVnWr2ZkYQuKsfhH7/aBkXPUMVMF8NkqcreoTKQKocK9Z13eEWlIYfWbPGGCio+RZubxhitCQAnRmHhQbJIImenL9GZPAqrNqmw4OCTK7vlILib4Zgl9reCC3yLzzw+mcVRb7ZbkT7YgKBYQYAgiU074PGx3q/iK7QHkgXsiNxjM4mAhWZEpXeqtLxdVjnKDUoV0YWVbgHJR1EbcgHKtpfZzuxoeXo5PzxBTzOqUZ26YryRi24FbZn3x2xuUF69QPUZvpu0aPX6Y3xzEp4FsUc+0k8XEpZTcHFwlUQtVSdj2G3E+Gaw8GOAt8+zzycS7AW+fISuBZhzucStJwhnmkgvXa7LkzIpEVWbI="

jobs:
  include:
    - name: "linux-gcc"
      compiler: gcc
      addons:
        <<: *addons_base
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - lcov
            # sfml dependencies
            - libx11-dev
            - libxrandr-dev
            - libxi-dev
            - libudev-dev
            - libgl1-mesa-dev
      env:
        - CC=/usr/bin/gcc-9
        - CXX=/usr/bin/g++-9
        - CMAKE_ARGS="-DENABLE_TESTING=ON -DENABLE_COVERAGE=ON -DWITH_LIBCXX=OFF"
        - REPORT_COVERAGE=1

    - name: "linux-clang"
      compiler: clang
      addons:
        <<: *addons_base
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
            # sfml dependencies
            - libx11-dev
            - libxrandr-dev
            - libxi-dev
            - libudev-dev
            - libgl1-mesa-dev
      env:
        - CC=/usr/bin/clang-9
        - CXX=/usr/bin/clang++-9
        - CMAKE_ARGS="-DWITH_LIBCXX=ON"
        - REPORT_COVERAGE=0

before_script:
  - git clone https://github.com/Microsoft/vcpkg.git
  - export VCPKG_ROOT=$(pwd)/vcpkg
  - echo "vcpkg installed at $VCPKG_ROOT"
  - cd $VCPKG_ROOT
  - $VCPKG_ROOT/bootstrap-vcpkg.sh -disableMetrics
  - $VCPKG_ROOT/vcpkg integrate install
  - $VCPKG_ROOT/vcpkg install gtest spdlog fmt sfml sdl2 magic-enum
  - pip install --user cmake ninja
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake -G Ninja --config Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_PATH/scripts/buildsystems/vcpkg.cmake $CMAKE_ARGS ..
  - |
    if [ "$REPORT_COVERAGE" = "1" ]; then
      build-wrapper-linux-x86-64 --out-dir bw-output cmake --build . -- -j $(nproc)
      ctest -V --output-on-failure
      sonar-scanner
      bash ../scripts/report_coverage.sh
    else
      cmake --build . -- -j $(nproc)
    fi

before_deploy:
  - tar -czvf "gameboy-$TRAVIS_OS_NAME-$TRAVIS_COMPILER.tar.gz" ./bin/*
  - cd ..
  - git config --local user.name  "emrsmsrli"
  - git config --local user.email "emrsmsrli1@gmail.com"
  - export RELEASE_TAG=release-$(head -1 gameboy/CMakeLists.txt | awk '{print $3}')
  - git tag $RELEASE_TAG

deploy:
  provider: releases
  api_key:
    secure: fN18Vwf2TY5blbIx9rNFA1YaP9LW1PnUorSf6jCkFpTpkU7V6J6CF2nSDTjDWJdj0Pf+7nu5laZ6Pd9CwHhkjuGW8iKK0O7ZG7gcM3aicD7msJihR3evzCDtAnW9qxOtZvMJ9XrIQ20DKVaV4s1i7v1ojKlhir+5m8GCoSvc3pt1j2QREypi1hHVJVRtgOXDun5BKwBbyCy2uHSGW6T4NrmA9usejdpaTaJFq2u6VpwsKtmBcoO2+km3OW/MQHFl+KsOsHUNaNAh2ryHjerXD9+Mf13JC11IvKEAGSjGhsrG3tZOXxEWFI+KdktzXh+9ZZLZMUCNeTsbNIlgUpp74vXvoWrbu3a0WsfjUEI7NSUIo86KuSctHLCC0xBQfLGoINdXvVjIdkJIv0eQhxZ4PftOJeJmg8ypYz3U0UFdUMQzE1QXtYBTx8ONpQyTifoRXawNzVzd2vwHURLpZE6jBLNSgJ+xgEhNvRPm8nfBplmldtXGvPQ8UxG4KDcMFzy1IZSbv7ZR06lsz2LlR9XKw7IwSnSiwVImXiG+4SUrKWXcC2qXqbwxc5E+yxBT5i2cqMaHTq6LgacS7SU0xAMzlYoIxdbpSZl8RjTDIIzBFGnICr4cWqCkunTIgNijtoWFr9u5LSasQgolJqoLP+30tDVZW/lJeicQpMYr4FbDgpk=
  file: "gameboy-$TRAVIS_OS_NAME-$TRAVIS_COMPILER.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    condition: $REPORT_COVERAGE = 0
