dist: xenial
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      python: 3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9"

    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-tes
    #         - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
    #           key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    #       packages:
    #         - clang-9
    #   env:
    #     - MATRIX_EVAL="CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user conan cmake ninja

script:
  - pip install --user conan
  - cmake -G Ninja -DENABLE_IPO=OFF .
  - cmake --build . --target gameboy

deploy:
  provider: releases
  api_key:
    secure: fJbeMJdHr9luQhHSvF6s58RXGWqFzDCyzcV3CTo5ipupTPuEFCm/EVg9cEihXKg8cCkABubWKRhyfUn0BzOqyclE+bYJDmxsA2AkNtwgfD8OJx3k7wmVKyzVRqA4EsIQ3ksqJ+oMcYDWwpSMAepwoZp2jJIYNEqYFjSi/N/omEaG6BJtWrx+fg+saFsF5rmgOQrQQSZAjaneCJ/w5COBX6ef3yZCTth/V2Tuzix4wO7zfr0ol1WGdxLXkLVuROyxCpltb/LB3cOscMSoQyPzwdvd5rUJw1B3+VK62UiCCZWztOPqaNAxemh30ykisE5ysjT/kvK0OHNzmOMFD/huFzdxgTakDn5DgT4VUouyn3ffIDolcbS0X0feFfeG00IAGfu2gD8/KSceL0xiIo8z0o+/Iyw5KAjD8CcJ4c5nPlKkN7XfUa2WTz5ON3z8JBvFatFcoTJmlPKrB13pquSWRSlpXoK7Fex0CHrXtxf1Nov+nT74289HQupyAglI2FGzwd+n89O2rB08DSrEWonsrvprIak6n5hCLANBkQXbwANHf9NYuuyZW5tejiM5Pf/Tlqx35G0r0a8MwGWTwpglRKhl4Y04HZcMEnThz68jW7qd/XHGnZtHNalMTvFXevR4ZCaoHgA75qIAWZAhPEuhEfSwxsIX5YcTRtFLL/YcwOg=
  file: "./bin/gameboy"
  skip_cleanup: true
  on:
    branch: master
