dist: xenial
sudo: false
language: cpp
python: 3.7

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CXX=/usr/bin/g++-10 CC=/usr/bin/gcc-10"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-tes
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip install --user conan cmake ninja

script:
  - pip install --user conan
  - cmake -G Ninja -DENABLE_IPO=OFF .
  - cmake --build .
