dist: xenial
sudo: false
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      python: 3.8
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CXX=/usr/bin/g++-9 CC=/usr/bin/gcc-9"

    - os: linux
      python: 3.8
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
      env:
        - MATRIX_EVAL="CXX=/usr/bin/clang++-9 CC=/usr/bin/clang-9"

before_script:
  - eval "${MATRIX_EVAL}"
  - pip install --user conan cmake ninja

script:
  - cmake -G Ninja -DENABLE_IPO=OFF .
  - cmake --build . --target gameboy

before_deploy:
  - git config --local user.name  "emrsmsrli"
  - git config --local user.email "emrsmsrli1@gmail.com"
  - export RELEASE_TAG=release-$(head -1 gameboy/CMakeLists.txt | awk '{print $3}')-$(git log --format=%h -1)
  - git tag $RELEASE_TAG

deploy:
  provider: releases
  api_key:
    secure: fN18Vwf2TY5blbIx9rNFA1YaP9LW1PnUorSf6jCkFpTpkU7V6J6CF2nSDTjDWJdj0Pf+7nu5laZ6Pd9CwHhkjuGW8iKK0O7ZG7gcM3aicD7msJihR3evzCDtAnW9qxOtZvMJ9XrIQ20DKVaV4s1i7v1ojKlhir+5m8GCoSvc3pt1j2QREypi1hHVJVRtgOXDun5BKwBbyCy2uHSGW6T4NrmA9usejdpaTaJFq2u6VpwsKtmBcoO2+km3OW/MQHFl+KsOsHUNaNAh2ryHjerXD9+Mf13JC11IvKEAGSjGhsrG3tZOXxEWFI+KdktzXh+9ZZLZMUCNeTsbNIlgUpp74vXvoWrbu3a0WsfjUEI7NSUIo86KuSctHLCC0xBQfLGoINdXvVjIdkJIv0eQhxZ4PftOJeJmg8ypYz3U0UFdUMQzE1QXtYBTx8ONpQyTifoRXawNzVzd2vwHURLpZE6jBLNSgJ+xgEhNvRPm8nfBplmldtXGvPQ8UxG4KDcMFzy1IZSbv7ZR06lsz2LlR9XKw7IwSnSiwVImXiG+4SUrKWXcC2qXqbwxc5E+yxBT5i2cqMaHTq6LgacS7SU0xAMzlYoIxdbpSZl8RjTDIIzBFGnICr4cWqCkunTIgNijtoWFr9u5LSasQgolJqoLP+30tDVZW/lJeicQpMYr4FbDgpk=
  file: "./bin/gameboy"
  skip_cleanup: true
  on:
    branch: master
