#ifndef GAMEBOY_INSTRUCTION_INFO_H
#define GAMEBOY_INSTRUCTION_INFO_H

#include <cstdint>
#include <array>
#include <string_view>

namespace gameboy::instruction {

struct info {
    uint8_t length = 0u;
    uint8_t cycle_count = 0u;
    std::string_view mnemonic = "invalid";
};

static constexpr std::array standard_instruction_set{
    info{1, 4, "NOP"},
    info{3, 12, "LD BC,{:#06x}"},
    info{1, 8, "LD (BC),A"},
    info{1, 8, "INC BC"},
    info{1, 4, "INC B"},
    info{1, 4, "DEC B"},
    info{2, 8, "LD B,{:#04x}"},
    info{1, 4, "RLCA"},
    info{3, 20, "LD ({:#06x}),SP"},
    info{1, 8, "ADD HL,BC"},
    info{1, 8, "LD A,(BC)"},
    info{1, 8, "DEC BC"},
    info{1, 4, "INC C"},
    info{1, 4, "DEC C"},
    info{2, 8, "LD C,{:#04x}"},
    info{1, 4, "RRCA"},

    info{2, 4, "STOP 0"},
    info{3, 12, "LD DE,{:#06x}"},
    info{1, 8, "LD (DE),A"},
    info{1, 8, "INC DE"},
    info{1, 4, "INC D"},
    info{1, 4, "DEC D"},
    info{2, 8, "LD D,{:#04x}"},
    info{1, 4, "RLA"},
    info{2, 12, "JR {:#04x}"},
    info{1, 8, "ADD HL,DE"},
    info{1, 8, "LD A,(DE)"},
    info{1, 8, "DEC DE"},
    info{1, 4, "INC E"},
    info{1, 4, "DEC E"},
    info{2, 8, "LD E,{:#04x}"},
    info{1, 4, "RRA"},

    info{2, 12, "JR NZ,{:#04x}"},
    info{3, 12, "LD HL,{:#06x}"},
    info{1, 8, "LD (HL+),A"},
    info{1, 8, "INC HL"},
    info{1, 4, "INC H"},
    info{1, 4, "DEC H"},
    info{2, 8, "LD H,{:#04x}"},
    info{1, 4, "DAA"},
    info{2, 12, "JR Z,{:#04x}"},
    info{1, 8, "ADD HL,HL"},
    info{1, 8, "LD A,(HL+)"},
    info{1, 8, "DEC HL"},
    info{1, 4, "INC L"},
    info{1, 4, "DEC L"},
    info{2, 8, "LD L,{:#04x}"},
    info{1, 4, "CPL"},

    info{2, 12, "JR NC,{:#04x}"},
    info{3, 12, "LD SP,{:#06x}"},
    info{1, 8, "LD (HL-),A"},
    info{1, 8, "INC SP"},
    info{1, 12, "INC (HL)"},
    info{1, 12, "DEC (HL)"},
    info{2, 12, "LD (HL),{:#04x}"},
    info{1, 4, "SCF"},
    info{2, 12, "JR C,{:#04x}"},
    info{1, 8, "ADD HL,SP"},
    info{1, 8, "LD A,(HL-)"},
    info{1, 8, "DEC SP"},
    info{1, 4, "INC A"},
    info{1, 4, "DEC A"},
    info{2, 8, "LD A,{:#04x}"},
    info{1, 4, "CCF"},

    info{1, 4, "LD B,B"},
    info{1, 4, "LD B,C"},
    info{1, 4, "LD B,D"},
    info{1, 4, "LD B,E"},
    info{1, 4, "LD B,H"},
    info{1, 4, "LD B,L"},
    info{1, 8, "LD B,(HL)"},
    info{1, 4, "LD B,A"},
    info{1, 4, "LD C,B"},
    info{1, 4, "LD C,C"},
    info{1, 4, "LD C,D"},
    info{1, 4, "LD C,E"},
    info{1, 4, "LD C,H"},
    info{1, 4, "LD C,L"},
    info{1, 8, "LD C,(HL)"},
    info{1, 4, "LD C,A"},

    info{1, 4, "LD D,B"},
    info{1, 4, "LD D,C"},
    info{1, 4, "LD D,D"},
    info{1, 4, "LD D,E"},
    info{1, 4, "LD D,H"},
    info{1, 4, "LD D,L"},
    info{1, 8, "LD D,(HL)"},
    info{1, 4, "LD D,A"},
    info{1, 4, "LD E,B"},
    info{1, 4, "LD E,C"},
    info{1, 4, "LD E,D"},
    info{1, 4, "LD E,E"},
    info{1, 4, "LD E,H"},
    info{1, 4, "LD E,L"},
    info{1, 8, "LD E,(HL)"},
    info{1, 4, "LD E,A"},

    info{1, 4, "LD H,B"},
    info{1, 4, "LD H,C"},
    info{1, 4, "LD H,D"},
    info{1, 4, "LD H,E"},
    info{1, 4, "LD H,H"},
    info{1, 4, "LD H,L"},
    info{1, 8, "LD H,(HL)"},
    info{1, 4, "LD H,A"},
    info{1, 4, "LD L,B"},
    info{1, 4, "LD L,C"},
    info{1, 4, "LD L,D"},
    info{1, 4, "LD L,E"},
    info{1, 4, "LD L,H"},
    info{1, 4, "LD L,L"},
    info{1, 8, "LD L,(HL)"},
    info{1, 4, "LD L,A"},

    info{1, 8, "LD (HL),B"},
    info{1, 8, "LD (HL),C"},
    info{1, 8, "LD (HL),D"},
    info{1, 8, "LD (HL),E"},
    info{1, 8, "LD (HL),H"},
    info{1, 8, "LD (HL),L"},
    info{1, 4, "HALT"},
    info{1, 8, "LD (HL),A"},
    info{1, 4, "LD A,B"},
    info{1, 4, "LD A,C"},
    info{1, 4, "LD A,D"},
    info{1, 4, "LD A,E"},
    info{1, 4, "LD A,H"},
    info{1, 4, "LD A,L"},
    info{1, 8, "LD A,(HL)"},
    info{1, 4, "LD A,A"},

    info{1, 4, "ADD A,B"},
    info{1, 4, "ADD A,C"},
    info{1, 4, "ADD A,D"},
    info{1, 4, "ADD A,E"},
    info{1, 4, "ADD A,H"},
    info{1, 4, "ADD A,L"},
    info{1, 8, "ADD A,(HL)"},
    info{1, 4, "ADD A,A"},
    info{1, 4, "ADC A,B"},
    info{1, 4, "ADC A,C"},
    info{1, 4, "ADC A,D"},
    info{1, 4, "ADC A,E"},
    info{1, 4, "ADC A,H"},
    info{1, 4, "ADC A,L"},
    info{1, 8, "ADC A,(HL)"},
    info{1, 4, "ADC A,A"},

    info{1, 4, "SUB B"},
    info{1, 4, "SUB C"},
    info{1, 4, "SUB D"},
    info{1, 4, "SUB E"},
    info{1, 4, "SUB H"},
    info{1, 4, "SUB L"},
    info{1, 8, "SUB (HL)"},
    info{1, 4, "SUB A"},
    info{1, 4, "SBC A,B"},
    info{1, 4, "SBC A,C"},
    info{1, 4, "SBC A,D"},
    info{1, 4, "SBC A,E"},
    info{1, 4, "SBC A,H"},
    info{1, 4, "SBC A,L"},
    info{1, 8, "SBC A,(HL)"},
    info{1, 4, "SBC A,A"},

    info{1, 4, "AND B"},
    info{1, 4, "AND C"},
    info{1, 4, "AND D"},
    info{1, 4, "AND E"},
    info{1, 4, "AND H"},
    info{1, 4, "AND L"},
    info{1, 8, "AND (HL)"},
    info{1, 4, "AND A"},
    info{1, 4, "XOR B"},
    info{1, 4, "XOR C"},
    info{1, 4, "XOR D"},
    info{1, 4, "XOR E"},
    info{1, 4, "XOR H"},
    info{1, 4, "XOR L"},
    info{1, 8, "XOR (HL)"},
    info{1, 4, "XOR A"},

    info{1, 4, "OR B"},
    info{1, 4, "OR C"},
    info{1, 4, "OR D"},
    info{1, 4, "OR E"},
    info{1, 4, "OR H"},
    info{1, 4, "OR L"},
    info{1, 8, "OR (HL)"},
    info{1, 4, "OR A"},
    info{1, 4, "CP B"},
    info{1, 4, "CP C"},
    info{1, 4, "CP D"},
    info{1, 4, "CP E"},
    info{1, 4, "CP H"},
    info{1, 4, "CP L"},
    info{1, 8, "CP (HL)"},
    info{1, 4, "CP A"},

    info{1, 20, "RET NZ"},
    info{1, 12, "POP BC"},
    info{3, 16, "JP NZ,{:#06x}"},
    info{3, 16, "JP {:#06x}"},
    info{3, 24, "CALL NZ,{:#06x}"},
    info{1, 16, "PUSH BC"},
    info{2, 8, "ADD A,{:#04x}"},
    info{1, 16, "RST 0x00"},
    info{1, 20, "RET Z"},
    info{1, 16, "RET"},
    info{3, 16, "JP Z,{:#06x}"},
    info{1, 4, "PREFIX CB"},
    info{3, 24, "CALL Z,{:#06x}"},
    info{3, 24, "CALL {:#06x}"},
    info{2, 8, "ADC A,{:#04x}"},
    info{1, 16, "RST 0x08"},

    info{1, 20, "RET NC"},
    info{1, 12, "POP DE"},
    info{3, 16, "JP NC,{:#06x}"},
    info{}, // placeholder
    info{3, 24, "CALL NC,{:#06x}"},
    info{1, 16, "PUSH DE"},
    info{2, 8, "SUB {:#04x}"},
    info{1, 16, "RST 0x10"},
    info{1, 20, "RET C"},
    info{1, 16, "RETI"},
    info{3, 16, "JP C,{:#06x}"},
    info{}, // placeholder
    info{3, 24, "CALL C,{:#06x}"},
    info{}, // placeholder
    info{2, 8, "SBC A,{:#04x}"},
    info{1, 16, "RST 0x18"},

    info{2, 12, "LD (0xFF00+{:#04x}),A"},
    info{1, 12, "POP HL"},
    info{2, 8, "LD (0xFF00+C),A"},
    info{}, // placeholder
    info{}, // placeholder
    info{1, 16, "PUSH HL"},
    info{2, 8, "AND {:#04x}"},
    info{1, 16, "RST 0x20"},
    info{2, 16, "ADD SP,{:#04x}"},
    info{1, 4, "JP (HL)"},
    info{3, 16, "LD ({:#06x}),A"},
    info{}, // placeholder
    info{}, // placeholder
    info{}, // placeholder
    info{2, 8, "XOR {:#04x}"},
    info{1, 16, "RST 0x28"},

    info{2, 12, "LD A,(0xFF00+{:#04x})"},
    info{1, 12, "POP AF"},
    info{2, 8, "LD A,(0xFF00+C)"},
    info{1, 4, "DI"},
    info{}, // placeholder
    info{1, 16, "PUSH AF"},
    info{2, 8, "OR {:#04x}"},
    info{1, 16, "RST 0x30"},
    info{2, 12, "LD HL,SP+{:#04x}"},
    info{1, 8, "LD SP,HL"},
    info{3, 16, "LD A,({:#06x})"},
    info{1, 4, "EI"},
    info{}, // placeholder
    info{}, // placeholder
    info{2, 8, "CP {:#04x}"},
    info{1, 16, "RST 0x38"}
};

static constexpr std::array extended_instruction_set{
    info{1, 8, "RLC B"},
    info{1, 8, "RLC C"},
    info{1, 8, "RLC D"},
    info{1, 8, "RLC E"},
    info{1, 8, "RLC H"},
    info{1, 8, "RLC L"},
    info{1, 16, "RLC (HL)"},
    info{1, 8, "RLC A"},
    info{1, 8, "RRC B"},
    info{1, 8, "RRC C"},
    info{1, 8, "RRC D"},
    info{1, 8, "RRC E"},
    info{1, 8, "RRC H"},
    info{1, 8, "RRC L"},
    info{1, 16, "RRC (HL)"},
    info{1, 8, "RRC A"},

    info{1, 8, "RL B"},
    info{1, 8, "RL C"},
    info{1, 8, "RL D"},
    info{1, 8, "RL E"},
    info{1, 8, "RL H"},
    info{1, 8, "RL L"},
    info{1, 16, "RL (HL)"},
    info{1, 8, "RL A"},
    info{1, 8, "RR B"},
    info{1, 8, "RR C"},
    info{1, 8, "RR D"},
    info{1, 8, "RR E"},
    info{1, 8, "RR H"},
    info{1, 8, "RR L"},
    info{1, 16, "RR (HL)"},
    info{1, 8, "RR A"},

    info{1, 8, "SLA B"},
    info{1, 8, "SLA C"},
    info{1, 8, "SLA D"},
    info{1, 8, "SLA E"},
    info{1, 8, "SLA H"},
    info{1, 8, "SLA L"},
    info{1, 16, "SLA (HL)"},
    info{1, 8, "SLA A"},
    info{1, 8, "SRA B"},
    info{1, 8, "SRA C"},
    info{1, 8, "SRA D"},
    info{1, 8, "SRA E"},
    info{1, 8, "SRA H"},
    info{1, 8, "SRA L"},
    info{1, 16, "SRA (HL)"},
    info{1, 8, "SRA A"},

    info{1, 8, "SWAP B"},
    info{1, 8, "SWAP C"},
    info{1, 8, "SWAP D"},
    info{1, 8, "SWAP E"},
    info{1, 8, "SWAP H"},
    info{1, 8, "SWAP L"},
    info{1, 16, "SWAP (HL)"},
    info{1, 8, "SWAP A"},
    info{1, 8, "SRL B"},
    info{1, 8, "SRL C"},
    info{1, 8, "SRL D"},
    info{1, 8, "SRL E"},
    info{1, 8, "SRL H"},
    info{1, 8, "SRL L"},
    info{1, 16, "SRL (HL)"},
    info{1, 8, "SRL A"},

    info{1, 8, "BIT 0,B"},
    info{1, 8, "BIT 0,C"},
    info{1, 8, "BIT 0,D"},
    info{1, 8, "BIT 0,E"},
    info{1, 8, "BIT 0,H"},
    info{1, 8, "BIT 0,L"},
    info{1, 16, "BIT 0,(HL)"},
    info{1, 8, "BIT 0,A"},
    info{1, 8, "BIT 1,B"},
    info{1, 8, "BIT 1,C"},
    info{1, 8, "BIT 1,D"},
    info{1, 8, "BIT 1,E"},
    info{1, 8, "BIT 1,H"},
    info{1, 8, "BIT 1,L"},
    info{1, 16, "BIT 1,(HL)"},
    info{1, 8, "BIT 1,A"},

    info{1, 8, "BIT 2,B"},
    info{1, 8, "BIT 2,C"},
    info{1, 8, "BIT 2,D"},
    info{1, 8, "BIT 2,E"},
    info{1, 8, "BIT 2,H"},
    info{1, 8, "BIT 2,L"},
    info{1, 16, "BIT 2,(HL)"},
    info{1, 8, "BIT 2,A"},
    info{1, 8, "BIT 3,B"},
    info{1, 8, "BIT 3,C"},
    info{1, 8, "BIT 3,D"},
    info{1, 8, "BIT 3,E"},
    info{1, 8, "BIT 3,H"},
    info{1, 8, "BIT 3,L"},
    info{1, 16, "BIT 3,(HL)"},
    info{1, 8, "BIT 3,A"},

    info{1, 8, "BIT 4,B"},
    info{1, 8, "BIT 4,C"},
    info{1, 8, "BIT 4,D"},
    info{1, 8, "BIT 4,E"},
    info{1, 8, "BIT 4,H"},
    info{1, 8, "BIT 4,L"},
    info{1, 16, "BIT 4,(HL)"},
    info{1, 8, "BIT 4,A"},
    info{1, 8, "BIT 5,B"},
    info{1, 8, "BIT 5,C"},
    info{1, 8, "BIT 5,D"},
    info{1, 8, "BIT 5,E"},
    info{1, 8, "BIT 5,H"},
    info{1, 8, "BIT 5,L"},
    info{1, 16, "BIT 5,(HL)"},
    info{1, 8, "BIT 5,A"},

    info{1, 8, "BIT 6,B"},
    info{1, 8, "BIT 6,C"},
    info{1, 8, "BIT 6,D"},
    info{1, 8, "BIT 6,E"},
    info{1, 8, "BIT 6,H"},
    info{1, 8, "BIT 6,L"},
    info{1, 16, "BIT 6,(HL)"},
    info{1, 8, "BIT 6,A"},
    info{1, 8, "BIT 7,B"},
    info{1, 8, "BIT 7,C"},
    info{1, 8, "BIT 7,D"},
    info{1, 8, "BIT 7,E"},
    info{1, 8, "BIT 7,H"},
    info{1, 8, "BIT 7,L"},
    info{1, 16, "BIT 7,(HL)"},
    info{1, 8, "BIT 7,A"},

    info{1, 8, "RES 0,B"},
    info{1, 8, "RES 0,C"},
    info{1, 8, "RES 0,D"},
    info{1, 8, "RES 0,E"},
    info{1, 8, "RES 0,H"},
    info{1, 8, "RES 0,L"},
    info{1, 16, "RES 0,(HL)"},
    info{1, 8, "RES 0,A"},
    info{1, 8, "RES 1,B"},
    info{1, 8, "RES 1,C"},
    info{1, 8, "RES 1,D"},
    info{1, 8, "RES 1,E"},
    info{1, 8, "RES 1,H"},
    info{1, 8, "RES 1,L"},
    info{1, 16, "RES 1,(HL)"},
    info{1, 8, "RES 1,A"},

    info{1, 8, "RES 2,B"},
    info{1, 8, "RES 2,C"},
    info{1, 8, "RES 2,D"},
    info{1, 8, "RES 2,E"},
    info{1, 8, "RES 2,H"},
    info{1, 8, "RES 2,L"},
    info{1, 16, "RES 2,(HL)"},
    info{1, 8, "RES 2,A"},
    info{1, 8, "RES 3,B"},
    info{1, 8, "RES 3,C"},
    info{1, 8, "RES 3,D"},
    info{1, 8, "RES 3,E"},
    info{1, 8, "RES 3,H"},
    info{1, 8, "RES 3,L"},
    info{1, 16, "RES 3,(HL)"},
    info{1, 8, "RES 3,A"},

    info{1, 8, "RES 4,B"},
    info{1, 8, "RES 4,C"},
    info{1, 8, "RES 4,D"},
    info{1, 8, "RES 4,E"},
    info{1, 8, "RES 4,H"},
    info{1, 8, "RES 4,L"},
    info{1, 16, "RES 4,(HL)"},
    info{1, 8, "RES 4,A"},
    info{1, 8, "RES 5,B"},
    info{1, 8, "RES 5,C"},
    info{1, 8, "RES 5,D"},
    info{1, 8, "RES 5,E"},
    info{1, 8, "RES 5,H"},
    info{1, 8, "RES 5,L"},
    info{1, 16, "RES 5,(HL)"},
    info{1, 8, "RES 5,A"},

    info{1, 8, "RES 6,B"},
    info{1, 8, "RES 6,C"},
    info{1, 8, "RES 6,D"},
    info{1, 8, "RES 6,E"},
    info{1, 8, "RES 6,H"},
    info{1, 8, "RES 6,L"},
    info{1, 16, "RES 6,(HL)"},
    info{1, 8, "RES 6,A"},
    info{1, 8, "RES 7,B"},
    info{1, 8, "RES 7,C"},
    info{1, 8, "RES 7,D"},
    info{1, 8, "RES 7,E"},
    info{1, 8, "RES 7,H"},
    info{1, 8, "RES 7,L"},
    info{1, 16, "RES 7,(HL)"},
    info{1, 8, "RES 7,A"},

    info{1, 8, "SET 0,B"},
    info{1, 8, "SET 0,C"},
    info{1, 8, "SET 0,D"},
    info{1, 8, "SET 0,E"},
    info{1, 8, "SET 0,H"},
    info{1, 8, "SET 0,L"},
    info{1, 16, "SET 0,(HL)"},
    info{1, 8, "SET 0,A"},
    info{1, 8, "SET 1,B"},
    info{1, 8, "SET 1,C"},
    info{1, 8, "SET 1,D"},
    info{1, 8, "SET 1,E"},
    info{1, 8, "SET 1,H"},
    info{1, 8, "SET 1,L"},
    info{1, 16, "SET 1,(HL)"},
    info{1, 8, "SET 1,A"},

    info{1, 8, "SET 2,B"},
    info{1, 8, "SET 2,C"},
    info{1, 8, "SET 2,D"},
    info{1, 8, "SET 2,E"},
    info{1, 8, "SET 2,H"},
    info{1, 8, "SET 2,L"},
    info{1, 16, "SET 2,(HL)"},
    info{1, 8, "SET 2,A"},
    info{1, 8, "SET 3,B"},
    info{1, 8, "SET 3,C"},
    info{1, 8, "SET 3,D"},
    info{1, 8, "SET 3,E"},
    info{1, 8, "SET 3,H"},
    info{1, 8, "SET 3,L"},
    info{1, 16, "SET 3,(HL)"},
    info{1, 8, "SET 3,A"},

    info{1, 8, "SET 4,B"},
    info{1, 8, "SET 4,C"},
    info{1, 8, "SET 4,D"},
    info{1, 8, "SET 4,E"},
    info{1, 8, "SET 4,H"},
    info{1, 8, "SET 4,L"},
    info{1, 16, "SET 4,(HL)"},
    info{1, 8, "SET 4,A"},
    info{1, 8, "SET 5,B"},
    info{1, 8, "SET 5,C"},
    info{1, 8, "SET 5,D"},
    info{1, 8, "SET 5,E"},
    info{1, 8, "SET 5,H"},
    info{1, 8, "SET 5,L"},
    info{1, 16, "SET 5,(HL)"},
    info{1, 8, "SET 5,A"},

    info{1, 8, "SET 6,B"},
    info{1, 8, "SET 6,C"},
    info{1, 8, "SET 6,D"},
    info{1, 8, "SET 6,E"},
    info{1, 8, "SET 6,H"},
    info{1, 8, "SET 6,L"},
    info{1, 16, "SET 6,(HL)"},
    info{1, 8, "SET 6,A"},
    info{1, 8, "SET 7,B"},
    info{1, 8, "SET 7,C"},
    info{1, 8, "SET 7,D"},
    info{1, 8, "SET 7,E"},
    info{1, 8, "SET 7,H"},
    info{1, 8, "SET 7,L"},
    info{1, 16, "SET 7,(HL)"},
    info{1, 8, "SET 7,A"}
};

constexpr uint8_t get_false_branch_cycle_count(const uint8_t inst)
{
    switch(inst) {
        case 0x20u:
        case 0x28u:
        case 0x30u:
        case 0x38u:
        case 0xC0u:
        case 0xC8u:
        case 0xD0u:
        case 0xD8u:
            return 8u;
        case 0xC2u:
        case 0xC4u:
        case 0xCAu:
        case 0xCCu:
        case 0xD2u:
        case 0xD4u:
        case 0xDAu:
        case 0xDCu:
            return 12u;
        default:
            return 0u;
    }
}

} // namespace gameboy

#endif //GAMEBOY_INSTRUCTION_INFO_H
