set(ALL_COMPILER_FLAGS
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE)

foreach(COMPILER_FLAGS ${ALL_COMPILER_FLAGS})
    string(REPLACE "/MD" "/MT" ${COMPILER_FLAGS} "${${COMPILER_FLAGS}}")
endforeach()
