name: Gameboy CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v1
      with:
        path: build
        key: ${{ runner.os }}-cache

    - name: Setup
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip3 install wheel setuptools conan ninja

    - name: Configure
      run: |
        mkdir build && cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=FALSE -G Ninja ..

    - name: Build
      run: cmake --build .
